
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_ACCUMULATE_DEVICE_ID,
		XPAR_ACCUMULATE_BASEADDR,
		XPAR_ACCUMULATE_INTERRUPT_PRESENT,
		XPAR_ACCUMULATE_IS_DUAL
	},
	{
		XPAR_LED_DEVICE_ID,
		XPAR_LED_BASEADDR,
		XPAR_LED_INTERRUPT_PRESENT,
		XPAR_LED_IS_DUAL
	},
	{
		XPAR_SWITCHES_DEVICE_ID,
		XPAR_SWITCHES_BASEADDR,
		XPAR_SWITCHES_INTERRUPT_PRESENT,
		XPAR_SWITCHES_IS_DUAL
	}
};


